import type { QuestionList } from "./types";

export const pp: QuestionList = [
  // === Вариант 1 ===
  {
    questionId: 617,
    studentQuestionId: 88136,
    questionText: "Деление в столбик",
    motivationMessage: null,
    question: {
      Steps: [
        {
          Id: 0,
          D1: 63,
          D2: 35,
          CarryIn: 0,
          Sum: 1,
          CarryOut: 28,
          Hint: "Раздели 63 на 35",
          Side: "right",
          ParentHint: "",
        },
        {
          Id: 1,
          D1: 1,
          D2: 35,
          CarryIn: 0,
          Sum: 35,
          CarryOut: 28,
          Hint: "Умножь 1 на 35",
          Side: "left",
          ParentHint: "",
        },
        {
          Id: 2,
          D1: 63,
          D2: 35,
          CarryIn: 0,
          Sum: 28,
          CarryOut: 28,
          Hint: "Вычти из 63 число 35",
          Side: "left",
        },
        {
          Id: 3,
          D1: 28,
          D2: 0,
          CarryIn: 0,
          Sum: 280,
          CarryOut: 280,
          Hint: "Спусти цифру 0 вниз",
          Side: "left",
        },
        {
          Id: 4,
          D1: 280,
          D2: 35,
          CarryIn: 0,
          Sum: 8,
          CarryOut: 0,
          Hint: "Раздели 280 на 35",
          Side: "right",
        },
        {
          Id: 5,
          D1: 8,
          D2: 35,
          CarryIn: 0,
          Sum: 280,
          CarryOut: 0,
          Hint: "Умножь 8 на 35",
          Side: "left",
        },
        {
          Id: 6,
          D1: 280,
          D2: 280,
          CarryIn: 0,
          Sum: 0,
          CarryOut: 0,
          Hint: "Вычти из 280 число 280",
          Side: "left",
        },
      ],
      ResultDigitCount: 2,
      MathOperation: 3,
      Numbers: [630, 35],
    },
    steps: undefined,
    options: undefined,
    answerType: 0,
    correctAnswer: undefined,
    backgroundImg: "",
    questionImgs: undefined,
    level: 0,
    readable: false,
    questionReadText: "",
    hints: [],
    backgroundImg2: "",
  },

  // === Вариант 2 (945 ÷ 45 = 21) ===
  {
    questionId: 618,
    studentQuestionId: 88137,
    questionText: "Деление в столбик",
    motivationMessage: null,
    question: {
      Steps: [
        {
          Id: 0,
          D1: 94,
          D2: 45,
          CarryIn: 0,
          Sum: 2,
          CarryOut: 4,
          Hint: "Раздели 94 на 45",
          Side: "right",
        },
        {
          Id: 1,
          D1: 2,
          D2: 45,
          CarryIn: 0,
          Sum: 90,
          CarryOut: 4,
          Hint: "Умножь 2 на 45",
          Side: "left",
        },
        {
          Id: 2,
          D1: 94,
          D2: 90,
          CarryIn: 0,
          Sum: 4,
          CarryOut: 4,
          Hint: "Вычти из 94 число 90",
          Side: "left",
        },
        {
          Id: 3,
          D1: 4,
          D2: 0,
          CarryIn: 0,
          Sum: 45,
          CarryOut: 45,
          Hint: "Спусти цифру 5 вниз",
          Side: "left",
        },
        {
          Id: 4,
          D1: 45,
          D2: 45,
          CarryIn: 0,
          Sum: 1,
          CarryOut: 0,
          Hint: "Раздели 45 на 45",
          Side: "right",
        },
        {
          Id: 5,
          D1: 1,
          D2: 45,
          CarryIn: 0,
          Sum: 45,
          CarryOut: 0,
          Hint: "Умножь 1 на 45",
          Side: "left",
        },
        {
          Id: 6,
          D1: 45,
          D2: 45,
          CarryIn: 0,
          Sum: 0,
          CarryOut: 0,
          Hint: "Вычти из 45 число 45",
          Side: "left",
        },
      ],
      ResultDigitCount: 2,
      MathOperation: 3,
      Numbers: [945, 45],
    },
    steps: undefined,
    options: undefined,
    answerType: 0,
    correctAnswer: undefined,
    backgroundImg: "",
    questionImgs: undefined,
    level: 0,
    readable: false,
    questionReadText: "",
    hints: [],
    backgroundImg2: "",
  },

  // === Вариант 3 (816 ÷ 34 = 24) ===
  {
    questionId: 619,
    studentQuestionId: 88138,
    questionText: "Деление в столбик",
    motivationMessage: null,
    question: {
      Steps: [
        {
          Id: 0,
          D1: 81,
          D2: 34,
          CarryIn: 0,
          Sum: 2,
          CarryOut: 13,
          Hint: "Раздели 81 на 34",
          Side: "right",
        },
        {
          Id: 1,
          D1: 2,
          D2: 34,
          CarryIn: 0,
          Sum: 68,
          CarryOut: 13,
          Hint: "Умножь 2 на 34",
          Side: "left",
        },
        {
          Id: 2,
          D1: 81,
          D2: 68,
          CarryIn: 0,
          Sum: 13,
          CarryOut: 13,
          Hint: "Вычти из 81 число 68",
          Side: "left",
        },
        {
          Id: 3,
          D1: 13,
          D2: 0,
          CarryIn: 0,
          Sum: 136,
          CarryOut: 136,
          Hint: "Спусти цифру 6 вниз",
          Side: "left",
        },
        {
          Id: 4,
          D1: 136,
          D2: 34,
          CarryIn: 0,
          Sum: 4,
          CarryOut: 0,
          Hint: "Раздели 136 на 34",
          Side: "right",
        },
        {
          Id: 5,
          D1: 4,
          D2: 34,
          CarryIn: 0,
          Sum: 136,
          CarryOut: 0,
          Hint: "Умножь 4 на 34",
          Side: "left",
        },
        {
          Id: 6,
          D1: 136,
          D2: 136,
          CarryIn: 0,
          Sum: 0,
          CarryOut: 0,
          Hint: "Вычти из 136 число 136",
          Side: "left",
        },
      ],
      ResultDigitCount: 2,
      MathOperation: 3,
      Numbers: [816, 34],
    },
    steps: undefined,
    options: undefined,
    answerType: 0,
    correctAnswer: undefined,
    backgroundImg: "",
    questionImgs: undefined,
    level: 0,
    readable: false,
    questionReadText: "",
    hints: [],
    backgroundImg2: "",
  },
  // === Вариант 4 (98736 ÷ 48 = 2057) ===
  {
    questionId: 620,
    studentQuestionId: 88139,
    questionText: "Деление в столбик",
    motivationMessage: null,
    question: {
      Steps: [
        // 98 ÷ 48 = 2
        {
          Id: 0,
          D1: 98,
          D2: 48,
          CarryIn: 0,
          Sum: 2,
          CarryOut: 2, // остаток после вычитания 98-96
          Hint: "Раздели 98 на 48",
          Side: "right",
          ParentHint: "",
        },
        // 2 × 48 = 96
        {
          Id: 1,
          D1: 2,
          D2: 48,
          CarryIn: 0,
          Sum: 96,
          CarryOut: 2,
          Hint: "Умножь 2 на 48",
          Side: "left",
          ParentHint: "",
        },
        // 98 − 96 = 2
        {
          Id: 2,
          D1: 98,
          D2: 96,
          CarryIn: 0,
          Sum: 2,
          CarryOut: 2,
          Hint: "Вычти из 98 число 96",
          Side: "left",
          ParentHint: "",
        },
        // ↓ 7 → 27
        {
          Id: 3,
          D1: 2,
          D2: 0,
          CarryIn: 0,
          Sum: 27,
          CarryOut: 27,
          Hint: "Спусти цифру 7 вниз",
          Side: "left",
          ParentHint: "",
        },

        // 27 ÷ 48 = 0  (важный нулевой разряд в частном)
        {
          Id: 4,
          D1: 27,
          D2: 48,
          CarryIn: 0,
          Sum: 0,
          CarryOut: 27,
          Hint: "Раздели 27 на 48 (получится 0)",
          Side: "right",
          ParentHint: "",
        },
        // 0 × 48 = 0
        {
          Id: 5,
          D1: 0,
          D2: 48,
          CarryIn: 0,
          Sum: 0,
          CarryOut: 27,
          Hint: "Умножь 0 на 48",
          Side: "left",
          ParentHint: "",
        },
        // 27 − 0 = 27
        {
          Id: 6,
          D1: 27,
          D2: 0,
          CarryIn: 0,
          Sum: 27,
          CarryOut: 27,
          Hint: "Вычти из 27 число 0",
          Side: "left",
          ParentHint: "",
        },
        // ↓ 3 → 273
        {
          Id: 7,
          D1: 27,
          D2: 0,
          CarryIn: 0,
          Sum: 273,
          CarryOut: 273,
          Hint: "Спусти цифру 3 вниз",
          Side: "left",
          ParentHint: "",
        },

        // 273 ÷ 48 = 5
        {
          Id: 8,
          D1: 273,
          D2: 48,
          CarryIn: 0,
          Sum: 5,
          CarryOut: 33, // 273-240
          Hint: "Раздели 273 на 48",
          Side: "right",
          ParentHint: "",
        },
        // 5 × 48 = 240
        {
          Id: 9,
          D1: 5,
          D2: 48,
          CarryIn: 0,
          Sum: 240,
          CarryOut: 33,
          Hint: "Умножь 5 на 48",
          Side: "left",
          ParentHint: "",
        },
        // 273 − 240 = 33
        {
          Id: 10,
          D1: 273,
          D2: 240,
          CarryIn: 0,
          Sum: 33,
          CarryOut: 33,
          Hint: "Вычти из 273 число 240",
          Side: "left",
          ParentHint: "",
        },
        // ↓ 6 → 336
        {
          Id: 11,
          D1: 33,
          D2: 0,
          CarryIn: 0,
          Sum: 336,
          CarryOut: 336,
          Hint: "Спусти цифру 6 вниз",
          Side: "left",
          ParentHint: "",
        },

        // 336 ÷ 48 = 7
        {
          Id: 12,
          D1: 336,
          D2: 48,
          CarryIn: 0,
          Sum: 7,
          CarryOut: 0,
          Hint: "Раздели 336 на 48",
          Side: "right",
          ParentHint: "",
        },
        // 7 × 48 = 336
        {
          Id: 13,
          D1: 7,
          D2: 48,
          CarryIn: 0,
          Sum: 336,
          CarryOut: 0,
          Hint: "Умножь 7 на 48",
          Side: "left",
          ParentHint: "",
        },
        // 336 − 336 = 0
        {
          Id: 14,
          D1: 336,
          D2: 336,
          CarryIn: 0,
          Sum: 0,
          CarryOut: 0,
          Hint: "Вычти из 336 число 336",
          Side: "left",
          ParentHint: "",
        },
      ],
      ResultDigitCount: 4,
      MathOperation: 3,
      Numbers: [98736, 48],
    },
    steps: undefined,
    options: undefined,
    answerType: 0,
    correctAnswer: undefined,
    backgroundImg: "",
    questionImgs: undefined,
    level: 0,
    readable: false,
    questionReadText: "",
    hints: [],
    backgroundImg2: "",
  },
];
